// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byyhtblucejlxjrvzpzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5eWh0Ymx1Y2VqbHhqcnZ6cHpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjI1MjIsImV4cCI6MjA3MTg5ODUyMn0.xkCJg0ij-F3v7k7kAqGyk3DZ2Jg36rQdUFqhRMZyxZ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});